const PageNames = {
	HOME: '/',
	CATEGORY: '/categories/:catogoryId?',
	PRODUCT_DETAIL: '/product/:productId',
	CONTACT: '/contact',
	MY_CART: '/my-cart',
	NOT_FOUND: '/not_found',
};

const AppFlowActions = {
	CHANGE_TITLE: 'CHANGE_TITLE',

	// common request status
	SENDING_REQUEST: 'SENDING_REQUEST',
	REQUEST_ERROR: 'REQUEST_ERROR',

	// category
	GET_CATEGORIES_COMPLETE: 'GET_CATEGORIES_COMPLETE',
	GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
	// products
	GET_PRODUCTS_COMPLETE: 'GET_PRODUCTS_COMPLETE',
	GET_PRODUCTS_REQUEST: 'GET_PRODUCTS_REQUEST',
	GET_PRODUCTS_BY_CATEGORY_REQUEST: 'GET_PRODUCTS_BY_CATEGORY_REQUEST',
	GET_PRODUCTS_BY_CATEGORY_COMPLETE: 'GET_PRODUCTS_BY_CATEGORY_COMPLETE',
	GET_ONE_CATEGORY_REQUEST: 'GET_ONE_CATEGORY_REQUEST',
	GET_ONE_CATEGORY_COMPLETE: 'GET_ONE_CATEGORY_COMPLETE',
	GET_PRODUCT_DETAIL_REQUEST: 'GET_PRODUCT_DETAIL_REQUEST',
	GET_PRODUCT_DETAIL_COMPLETE: 'GET_PRODUCT_DETAIL_COMPLETE',
	ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
	ADD_TO_CART_COMPLETE: 'ADD_TO_CART_COMPLETE',
	REMOVE_FROM_CART_REEQUEST: 'REMOVE_FROM_CART_REQUEST',
	REMOVE_FROM_CART_COMPLETE: 'REMOVE_FROM_CART_COMPLETE',
}


export {
	PageNames,
	AppFlowActions,
};
