const PageNames = {
	HOME: '/',
	CATEGORY: '/categories',
	PRODUCT_DETAIL: '/product/:productId',
	CONTACT: '/contact',
	NOT_FOUND: '/not_found',
};

const AppFlowActions = {
	CHANGE_TITLE: 'CHANGE_TITLE',

	// common request status
	SENDING_REQUEST: 'SENDING_REQUEST',
	REQUEST_ERROR: 'REQUEST_ERROR',

	// category
	GET_CATEGORIES_COMPLETE: 'GET_CATEGORIES_COMPLETE',
	GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
	// products
	GET_PRODUCTS_COMPLETE: 'GET_PRODUCTS_COMPLETE',
	GET_PRODUCTS_REQUEST: 'GET_PRODUCTS_REQUEST',
	GET_PRODUCTS_BY_CATEGORY_REQUEST: 'GET_PRODUCTS_BY_CATEGORY_REQUEST',
	GET_PRODUCTS_BY_CATEGORY_COMPLETE: 'GET_PRODUCTS_BY_CATEGORY_COMPLETE',
}


export {
	PageNames,
	AppFlowActions,
};
